### PR TITLE
Scif merge from personal repo

### PR DESCRIPTION
**Pull request by Chris-Schnaufer**
---
name: Pull Request
about: Fill out this template before submitting a Pull Request.
title: Updated for SciF and AgPypeline
labels: 'pull request'
assignees: ''
---

## Description

Ported to work with SciF and AgPypeline.

## Types of changes

Renamed transformer.py to `soilmask.py`
Moved configuration information to agpypeline.Configuration derived class
Moved Algorithm code into agpypeline.Algorithm derived class
Got rid of commented out code

## Checklist:

- [x] I have read the documentation on [CONTRIBUTING](https://github.com/AgPipeline/Organization-info) 
- [ ] My updates require a change to the documentation 
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [x] All new and existing tests passed

## Time frame for completing Pull Request (from creation date):
- [x] As soon as possible
- [ ] In the next two weeks
- [ ] In the next month

## Focus of Pull Request:
All comments are welcome regardless of which items are checked off.
- [ ] All of the below (no need to check off the other boxes)
- [x] There are no errors or inconsistencies
- [x] Everything appears clear and easy to understand
- [ ] Suggest improvements
- [ ] Identify areas where functionality and/or documentation is missing

## Hints to reviewers:

The renaming to `soilmask.py` happened before using agpypline library
Deleted files were either obsolete or were deleted when main branch replaced prototype files
Removing generate_docker.py and Dockerfile.template files will be done through another issue

### CODE REVIEW

**Comment by jvanderleeuw** [comment]
A packages.txt file is needed (can likely be copied from original branch). Also regarding naming conventions in the agpypeline library, I am wondering why entrypoint.entrypoint is called. I understand that it is a function in the entrypoint class but am wondering if it should be a subclass called Entrypoint (capital E) to preserve consistency. This is because in the other imports from soilmask.py, there is an algorithm.Algorithm and environment.Environment, but no equivalent for entrypoint.py

**Comment by Chris-Schnaufer** [comment]
@jvanderleeuw 
> ...wondering if it should be a subclass...

There isn't an inherent need for the entrypoint library code to be wrapped in a class. Perhaps a better function name is needed to clear up the confusion. Can you recommend one?

**Comment by jvanderleeuw** [comment]
I am not sure yet if the entrypoint function is used anywhere else besides in the transformer soilmask's soilmask.py file. If so, then perhaps the parser could be created within soilmask.py instead and the function in agpypeline not needed. 

If it is in fact needed, then the function could possibly be named set_parameters or create_entrypoint or begin_process (vs entrypoint so that the function does not have the same name as the .py file)

**Comment by Chris-Schnaufer** [comment]
I like `begin_process` since it's clear what it's about. I'm going to add an issue for renaming it

**Comment by dlebauer** [comment]
If the pylint action is working, shouldn't there be some checks on the pull request, i.e., here: https://github.com/AgPipeline/transformer-soilmask/pull/16/checks? If pylint fails, will it prevent merging a PR?

**Comment by Chris-Schnaufer** [comment]
> If the pylint action is working, shouldn't there be some checks on the pull request ...

@dlebauer The only automated checks are for the develop and main branches. Not testing on branches that aren't those allows developers greater freedom to use multiple branches to develop a solution without having the requirements that these branches have. If people are developing solutions in other organizations they should (potentially) be merging into develop.

**Comment by Chris-Schnaufer** [comment]
> If pylint fails, will it prevent merging a PR?
@dlebauer All the code repos should have "Require status checks to pass before merging" checked off in their setting for the protected branches. You can check that under: Settings -> Branches & choosing to edit a branch displayed

**Pull request merged**
