### PR TITLE
Tried to update algorithm

### PR DESCRIPTION
**Pull request by dlebauer**
copied from the transformer-soilmask repository and updated based on code in based on code on transformer.py

### CODE REVIEW

**Comment by dlebauer** [comment]
added images in https://github.com/AgPipeline/transformer-soilmask/pull/11/commits/7f8d63ed3f31d66d94c9a058633a8001b3b4b7f6

**Comment by jvanderleeuw** [comment]
For the updated README file in transformer-canopycover, I am not sure that the algorithm description section of the README file (which had a link to the Transformer Soil Mask algorithm) accurately reflects the calculate_canopycover_masked function in transformer.py. The algorithm described in Transformer Soil Mask takes in multiple parameters, including a G-R Threshold, Blur, Saturation threshold, and Small Area Threshold. In contrast, that of Transformer-Canopycover only takes in a numpy array and seems to do the last part of the described algorithm from Transformer Soil Mask.

**Comment by Chris-Schnaufer** [comment]
> For the updated README file in transformer-canopycover, I am not sure that the algorithm description section of the README file (which had a link to the Transformer Soil Mask algorithm) accurately reflects the calculate_canopycover_masked function in transformer.py. The algorithm described in Transformer Soil Mask takes in multiple parameters, including a G-R Threshold, Blur, Saturation threshold, and Small Area Threshold. In contrast, that of Transformer-Canopycover only takes in a numpy array and seems to do the last part of the described algorithm from Transformer Soil Mask.

@dlebauer Do you have a comment on this?

**Comment by dlebauer** [comment]
I spoke with @jvanderleeuw about that - he got the soil mask and canopy cover algorithms confused; this one does have the parameters he mentioned.

**Pull request merged**
